# Visualization Exercise

<img src="logo.jpg"/>

### **1.Explore Data**

In [2]:
#import libraries
import pandas as pd
import matplotlib as plt
import seaborn as sns
import numpy as np

In [10]:
#To take a look at the first five rows as default
import pandas as pd
df = pd.read_csv("Crime_data.csv")
df.head()

,Year,State,District,Rape Cases,Abduction Cases,Murder Cases,Total Crimes,Population,Crime Rate,Arrests,Crime Clearance Rate
0,2018,Goa,Vasco da Gama,21,125,38,355,601856,58.98,294,82.82
1,2019,Tamil Nadu,Coimbatore,136,114,76,730,454251,160.70,627,85.89
2,2019,Madhya Pradesh,Gwalior,133,178,71,748,1881680,39.75,549,273.40
3,2021,Haryana,Panipat,102,216,25,558,725939,76.87,435,77.96
4,2020,Tripura,Agartala,100,259,75,487,1630786,29.86,363,74.54

In [11]:
#To take a look at the last five rows as default
df.tail()

,Year,State,District,Rape Cases,Abduction Cases,Murder Cases,Total Crimes,Population,Crime Rate,Arrests,Crime Clearance Rate
2995,2019,Mizoram,Champhai,139,150,7,778,980131,79.38,620,79.69
2996,2019,Telangana,Warangal,19,300,72,833,685975,121.43,661,79.35
2997,2021,Arunachal Pradesh,Itanagar,22,136,20,439,677041,64.84,316,71.98
2998,2021,Manipur,Churachandpur,58,218,56,777,1970611,39.43,462,59.46
2999,2018,Daman and Diu,Vijayawada,75,277,56,905,390783,231.59,847,93.59

In [13]:
#print the summary of the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  3000 non-null   int64
 1   State                 3000 non-null   object
 2   District              3000 non-null   object
 3   Rape Cases            3000 non-null   int64
 4   Abduction Cases       3000 non-null   int64
 5   Murder Cases          3000 non-null   int64
 6   Total Crimes          3000 non-null   int64
 7   Population            3000 non-null   object
 8   Crime Rate            3000 non-null   float64
 9   Arrests               3000 non-null   int64
 10  Crime Clearance Rate  3000 non-null   float64
dtypes: float64(2), int64(6), object(3)
memory usage: 257.9+ KB

In [14]:
#Print the total number of rows and columns in the data set
print(f"Shape of dataset: {df.shape}")

Shape of dataset: (3000, 11)

In [15]:
# Shows basic statistics for each numerical column in the DataFrame
df.describe()

,Year,Rape Cases,Abduction Cases,Murder Cases,Total Crimes,Crime Rate,Arrests,Crime Clearance Rate
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,2019.987667,107.891000,158.363333,53.326333,592.809333,112.593547,448.536667,75.753130
std,1.404578,82.801182,82.425979,27.673256,168.284082,154.614185,161.435340,38.926365
min,2018.000000,10.000000,20.000000,5.000000,139.000000,9.920000,19.000000,0.450000
25%,2019.000000,56.750000,86.000000,29.000000,472.000000,38.820000,334.000000,62.375000
50%,2020.000000,107.000000,158.000000,53.000000,590.000000,59.415000,433.000000,74.870000
75%,2021.000000,153.000000,229.000000,77.000000,716.250000,115.177500,547.000000,87.770000
max,2022.000000,2183.000000,300.000000,100.000000,1043.000000,1706.020000,1524.000000,1584.230000

In [16]:
# Check for nan values if found then drop them
df.isnull().sum()
# removing Nan Value or missing values
df.dropna(inplace=True)
df.isnull().sum()

Year                    0
State                   0
District                0
Rape Cases              0
Abduction Cases         0
Murder Cases            0
Total Crimes            0
Population              0
Crime Rate              0
Arrests                 0
Crime Clearance Rate    0
dtype: int64

In [17]:
# Same for duplicates check for them first then drop if found any
df.duplicated().sum()
df = df.drop_duplicates()

In [18]:
#Count unique values
df.nunique()

Year                       5
State                     40
District                 104
Rape Cases               196
Abduction Cases          281
Murder Cases              96
Total Crimes             723
Population              2997
Crime Rate              2693
Arrests                  687
Crime Clearance Rate    2236
dtype: int64

### **2.Find the 5 states with the lowest and highest `crime rates`**

In [25]:
# find the 5 states with the lowest crime rates
print(df.columns)
lowest_crime_states = df.nsmallest(5, 'Crime Rate')
print(lowest_crime_states)

Index(['Year', 'State', 'District', 'Rape Cases', 'Abduction Cases',
       'Murder Cases', 'Total Crimes', 'Population', 'Crime Rate', 'Arrests',
       'Crime Clearance Rate'],
      dtype='object')
      Year           State     District  Rape Cases  Abduction Cases  \
1226  2020       Telangana    Nizamabad          77               26
1755  2018         Tripura  Kailashahar          27               38
2560  2019      Puducherry     Karaikal          15               99
1849  2019  Madhya Pradesh       Bhopal          53               29
981   2020          Punjab     Amritsar          10               95

      Murder Cases  Total Crimes Population  Crime Rate  Arrests  \
1226            25           196    1975935        9.92      179
1755            17           206    1905690       10.81      177
2560            17           196    1787360       10.97      141
1849            64           205    1827005       11.22     1119
981             18           220    1853314       11.87      211

      Crime Clearance Rate
1226                 91.33
1755                 85.92
2560                 71.94
1849                 58.05
981                  95.91

In [1]:
import matplotlib.pyplot as plt

# Create a bar plot to visualize the 5 states with the lowest crime rate
lowest_crime_states = df.nsmallest(5, 'Crime Rate')


# Set title and labels for the plot

plt.figure(figsize=(10, 5))
plt.bar(lowest_crime_states['State'], lowest_crime_states['Crime Rate'], color='green')
plt.xlabel('State')
plt.ylabel('Crime Rate')
plt.title('Top 5 States with Lowest Crime Rate')

plt.xticks(rotation=45)


# Display the plot
plt.show()

# Print your conclusions
print("Conclusion: ")

NameError: name 'df' is not defined

In [ ]:
# get the 5 states with the highest crime rates.
top_5_states = df.sort_values(by='Crime Rate', ascending=False).head(5)

In [ ]:
# Create a bar plot to visualize the 5 states with the Highest crime rate
plt.figure(figsize=(10, 6))
plt.bar(top_5_states['State'], top_5_states['Crime Rate'], color='red')

# Set title and labels for the plot

plt.title('Top 5 States with Highest Crime Rate', fontsize=14)
plt.xlabel('State', fontsize=12)
plt.ylabel('Crime Rate', fontsize=12)
# Display the plot
plt.show()

# Print your conclusions
print("Conclusion: ")

### **3.Find the sum of `Rape Cases` for each year**

In [ ]:
# Group the dataset by 'Year' and calculate the sum of 'Rape Cases' for each year
yearly_cases = df.groupby('Year')['Rape Cases'].sum()

# Plot the line chart showing the trend of total rape cases per year
plt.figure(figsize=(10, 6))
plt.plot(yearly_cases.index, yearly_cases.values, marker='o', linestyle='-', color='red')


# Title and labels for the plot
plt.title('Trend of Rape Cases per Year', fontsize=14)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Total Rape Cases', fontsize=12)
# Show the plot
plt.show()

# Print your conclusions from this plot
print("conclusions: ")

### **4.Find the correlation between `total crimes` and `population`**

In [ ]:
# Create a scatter plot with Population on the x-axis and Total Crimes on the y-axis
plt.figure(figsize=(10, 6))
plt.scatter(df['Population'], df['Total Crimes'], color='blue', alpha=0.6)
plt.grid(True)

# Set title and labels for the plot
plt.title('Correlation between Population and Total Crimes', fontsize=14)
plt.xlabel('Population', fontsize=12)
plt.ylabel('Total Crimes', fontsize=12)


# Show the plot
plt.show()

# Print your conclusions from this plot
print("conclusions: ")

### **5.Find out how the average of `crime clearance` rate vary across different `states`**

In [ ]:
# Group the data by 'State' and calculate the mean 'Crime Clearance Rate' for each state, then sort them in descending order
state_clearance_rates = df.groupby('State')['Crime Clearance Rate'].mean().sort_values(ascending=False)

# Create a bar plot using the calculated average crime clearance rates
plt.figure(figsize=(12, 6))
plt.bar(state_clearance_rates.index, state_clearance_rates.values, color='orange')


# Set the title and labels for the plot
plt.title('Average Crime Clearance Rate per State', fontsize=14)
plt.xlabel('State', fontsize=12)
plt.ylabel('Average Crime Clearance Rate', fontsize=12)


# Rotate x-axis labels (state names) to avoid overlap and ensure readability
plt.xticks(rotation=45, ha="right")


# Show the plot
plt.show()
# Print your conclusions from this plot
print("conclusions: ")

### **6.Find the Outliers of `abduction cases` in `western states`**

Note: wester states are 'Goa', 'Gujarat', 'Maharashtra', 'Rajasthan'

In [ ]:
# Defining the western states


# Filtering the dataset for western states
western_data = df[df['State'].isin(western_states)]


# Plot the boxplot for Abduction Cases in Western States
plt.figure(figsize=(8, 6))
plt.boxplot(western_data['Abduction Cases'], vert=False, patch_artist=True, boxprops=dict(facecolor="lightblue"))


# Set the title and labels for the plot
plt.title('Outliers in Abduction Cases in Western States', fontsize=14)
plt.xlabel('Number of Abduction Cases', fontsize=12)
plt.grid(True)

# Show the plot
plt.show()
# Print your conclusions from this plot
print("conclusions: ")

### **7.Find the trend in the number of `murder cases` over the `years`**

In [ ]:
# get the sum of the murder cases over the years
murder_trend = df.groupby('Year')['Murder Cases'].sum()


# Create a line plot with murder cases trend
plt.figure(figsize=(10, 5))
plt.plot(murder_trend.index, murder_trend.values, marker='o', linestyle='-', color='red')


# Set the title and labels for the plot
plt.title('Trend of Murder Cases Over the Years', fontsize=14)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Total Murder Cases', fontsize=12)
plt.grid(True)

# Show the plot
plt.show()
# Print your conclusions from this plot
print("conclusions: ")

### **8.Find out which `state` has highest number of `arrest`**

In [ ]:
#pick the top 10 states
arrest_by_state = df.groupby('State')['Arrests'].sum()

#barplot for the top 10 states
top_10_states = arrest_by_state.sort_values(ascending=False).head(10)
plt.figure(figsize=(12, 6))
plt.bar(top_10_states.index, top_10_states.values, color='skyblue')


# Set the title and labels
plt.title('Top 10 States with Highest Number of Arrests', fontsize=14)
plt.xlabel('State', fontsize=12)
plt.ylabel('Total Arrests', fontsize=12)
plt.xticks(rotation=45)

# Show the plot
plt.show()

# Print your conclusions from this plot
print("conclusions: ")

### **9.Find the average `crime rate` across southern states over the `years`**

Note: southern states are 'Andhra Pradesh', 'Telangana', 'Tamil Nadu', 'Karnataka', 'Kerala', 'Puducherry'

In [ ]:
#Southern States

southern_states = ['Andhra Pradesh', 'Telangana', 'Tamil Nadu', 'Karnataka', 'Kerala', 'Puducherry']
# Filter the dataset for Southern States
southern_data = df[df['State'].isin(southern_states)]


# Calculate the average crime rate by state and year
avg_crime_rate = southern_data.groupby('Year')['Crime Rate'].mean()

# Plot the line plot for Southern States

plt.figure(figsize=(10, 5))
plt.plot(avg_crime_rate.index, avg_crime_rate.values, marker='o', linestyle='-', color='b')

# Set title and labels
plt.title('Average Crime Rate in Southern States Over the Years', fontsize=14)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Average Crime Rate', fontsize=12)
plt.grid(True)

# Show the plot
plt.show()

# Print your conclusions from this plot
print("conclusions: ")

### **10.Find the Total number of `cases` for each crime type**

Note: cases are Rape cases, Abduction cases, Murder cases

In [ ]:
# Sum the cases for each crime type
crime_type_counts = df[['Rape Cases', 'Abduction Cases', 'Murder Cases']].sum()

# Plot the donut chart
plt.figure(figsize=(7, 7))
plt.pie(crime_type_counts, labels=crime_type_counts.index, autopct='%1.1f%%', startangle=90, wedgeprops={'edgecolor': 'white', 'linewidth': 2})
centre_circle = plt.Circle((0, 0), 0.70, fc='white')
plt.gca().add_artist(centre_circle)

# Set the title
plt.title('Total Number of Cases for Each Crime Type')


# Show the plot
plt.show()

# Print your conclusions from this plot
print("conclusions: ")

### **12.Find the Correlation Matrix of Crime Data**

In [ ]:
# Filter data to ensure only numeric data is left

numeric_df = df.select_dtypes(include=['number'])
# Calculate the correlation matrix
correlation_matrix = numeric_df.corr()

# Set up the visual style of the plot
plt.figure(figsize=(10, 8))
sns.set(style="whitegrid")

# Create the heatmap
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap="coolwarm", linewidths=0.5)


# Set the title
plt.title("Correlation Matrix of Crime Data")


# Display the plot
plt.show()
# Print your conclusions from this plot
print("conclusions: ")

#### **Overall conclusion:**  Write you amazing conclusions about this dataset after you made your analysis